<%@ page contentType="text/xml;charset=euc-kr"%>
<%
  StringBuffer strAd = new StringBuffer();
%>
<%
strAd.append("<?xml version=\"1.0\" encoding=\"EUC-KR\" standalone=\"no\"?>");
strAd.append("<ROOM>");
strAd.append("<ROOM_LIST>");
strAd.append("<ROOM_NM>외금강 주이어온돌</ROOM_NM>");
strAd.append("<ROOM_VAL>MHJRO</ROOM_VAL>");
strAd.append("<ROOM_PRI>200000</ROOM_PRI>");
strAd.append("<ROOM_REAL_NUM>2</ROOM_REAL_NUM>");
strAd.append("<ROOM_TOTAL_NUM>10</ROOM_TOTAL_NUM>");
strAd.append("<ROOM_IMG_S>http://www.nate.com/images/thumb/Enter11J/060607_07.gif</ROOM_IMG_S>");
strAd.append("<ROOM_INFO_S>외금강 주이어온돌 정보 입니다.</ROOM_INFO_S>");
strAd.append("<ROOM_GALLERY_LIST>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif</ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>1.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif</ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>2.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif</ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>3.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif</ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M></ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("</ROOM_GALLERY_LIST>");
strAd.append("<ROOM_REV_YN>Y(Y :가능, N:불가능)</ROOM_REV_YN>");
strAd.append("</ROOM_LIST>");

strAd.append("<ROOM_LIST>");
strAd.append("<ROOM_NM>외금강 스텐다드온돌</ROOM_NM>");
strAd.append("<ROOM_VAL>MHSTO</ROOM_VAL>");
strAd.append("<ROOM_PRI>200000</ROOM_PRI>");
strAd.append("<ROOM_REAL_NUM>2</ROOM_REAL_NUM>");
strAd.append("<ROOM_TOTAL_NUM>10</ROOM_TOTAL_NUM>");
strAd.append("<ROOM_IMG_S>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_S>");
strAd.append("<ROOM_INFO_S>외금강 스텐다드온돌 정보 입니다.</ROOM_INFO_S>");
strAd.append("<ROOM_GALLERY_LIST>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>1.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>2.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>3.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M></ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("</ROOM_GALLERY_LIST>");
strAd.append("<ROOM_REV_YN>Y</ROOM_REV_YN>");
strAd.append("</ROOM_LIST>");

strAd.append("<ROOM_LIST>");
strAd.append("<ROOM_NM>외금강 스텐다드트윈</ROOM_NM>");
strAd.append("<ROOM_VAL>MHSTT</ROOM_VAL>");
strAd.append("<ROOM_PRI>200000</ROOM_PRI>");
strAd.append("<ROOM_REAL_NUM>2</ROOM_REAL_NUM>");
strAd.append("<ROOM_TOTAL_NUM>10</ROOM_TOTAL_NUM>");
strAd.append("<ROOM_IMG_S>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_S>");
strAd.append("<ROOM_INFO_S>외금강 스텐다드트윈 정보 입니다.</ROOM_INFO_S>");
strAd.append("<ROOM_GALLERY_LIST>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>1.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>2.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>3.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M></ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("</ROOM_GALLERY_LIST>");
strAd.append("<ROOM_REV_YN>Y</ROOM_REV_YN>");
strAd.append("</ROOM_LIST>");

strAd.append("<ROOM_LIST>");
strAd.append("<ROOM_NM>외금강 스위트트윈</ROOM_NM>");
strAd.append("<ROOM_VAL>MHSWT</ROOM_VAL>");
strAd.append("<ROOM_PRI>200000</ROOM_PRI>");
strAd.append("<ROOM_REAL_NUM>2</ROOM_REAL_NUM>");
strAd.append("<ROOM_TOTAL_NUM>10</ROOM_TOTAL_NUM>");
strAd.append("<ROOM_IMG_S>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_S>");
strAd.append("<ROOM_INFO_S>외금강 스위트트윈 정보 입니다.</ROOM_INFO_S>");
strAd.append("<ROOM_GALLERY_LIST>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>1.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>2.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>3.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M></ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("</ROOM_GALLERY_LIST>");
strAd.append("<ROOM_REV_YN>Y</ROOM_REV_YN>");
strAd.append("</ROOM_LIST>");

strAd.append("<ROOM_LIST>");
strAd.append("<ROOM_NM>외금강 디럭스스위트</ROOM_NM>");
strAd.append("<ROOM_VAL>MHDST</ROOM_VAL>");
strAd.append("<ROOM_PRI>200000</ROOM_PRI>");
strAd.append("<ROOM_REAL_NUM>2</ROOM_REAL_NUM>");
strAd.append("<ROOM_TOTAL_NUM>10</ROOM_TOTAL_NUM>");
strAd.append("<ROOM_IMG_S>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_S>");
strAd.append("<ROOM_INFO_S>외금강 디럭스스위트 정보 입니다.</ROOM_INFO_S>");
strAd.append("<ROOM_GALLERY_LIST>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>1.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>2.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>3.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M></ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("</ROOM_GALLERY_LIST>");
strAd.append("<ROOM_REV_YN>Y</ROOM_REV_YN>");
strAd.append("</ROOM_LIST>");

strAd.append("<ROOM_LIST>");
strAd.append("<ROOM_NM>금강산호텔 - 로얄스위트</ROOM_NM>");
strAd.append("<ROOM_VAL>GHRST</ROOM_VAL>");
strAd.append("<ROOM_PRI>200000</ROOM_PRI>");
strAd.append("<ROOM_REAL_NUM>2</ROOM_REAL_NUM>");
strAd.append("<ROOM_TOTAL_NUM>10</ROOM_TOTAL_NUM>");
strAd.append("<ROOM_IMG_S>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_S>");
strAd.append("<ROOM_INFO_S>금강산호텔 - 로얄스위트 정보 입니다.</ROOM_INFO_S>");
strAd.append("<ROOM_GALLERY_LIST>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>1.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>2.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>3.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M></ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("</ROOM_GALLERY_LIST>");
strAd.append("<ROOM_REV_YN>Y</ROOM_REV_YN>");
strAd.append("</ROOM_LIST>");

strAd.append("<ROOM_LIST>");
strAd.append("<ROOM_NM>금강산호텔 - 디럭스스위트</ROOM_NM>");
strAd.append("<ROOM_VAL>GHDST</ROOM_VAL>");
strAd.append("<ROOM_PRI>200000</ROOM_PRI>");
strAd.append("<ROOM_REAL_NUM>2</ROOM_REAL_NUM>");
strAd.append("<ROOM_TOTAL_NUM>10</ROOM_TOTAL_NUM>");
strAd.append("<ROOM_IMG_S>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_S>");
strAd.append("<ROOM_INFO_S>금강산호텔 - 로얄스위트 정보 입니다.</ROOM_INFO_S>");
strAd.append("<ROOM_GALLERY_LIST>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>1.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>2.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>3.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M></ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("</ROOM_GALLERY_LIST>");
strAd.append("<ROOM_REV_YN>Y</ROOM_REV_YN>");
strAd.append("</ROOM_LIST>");

strAd.append("<ROOM_LIST>");
strAd.append("<ROOM_NM>금강산호텔 - 스위트(트윈)</ROOM_NM>");
strAd.append("<ROOM_VAL>GHSWT</ROOM_VAL>");
strAd.append("<ROOM_PRI>200000</ROOM_PRI>");
strAd.append("<ROOM_REAL_NUM>2</ROOM_REAL_NUM>");
strAd.append("<ROOM_TOTAL_NUM>10</ROOM_TOTAL_NUM>");
strAd.append("<ROOM_IMG_S>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_S>");
strAd.append("<ROOM_INFO_S>금강산호텔 - 스위트(트윈) 정보 입니다.</ROOM_INFO_S>");
strAd.append("<ROOM_GALLERY_LIST>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>1.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>2.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>3.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M></ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("</ROOM_GALLERY_LIST>");
strAd.append("<ROOM_REV_YN>Y</ROOM_REV_YN>");
strAd.append("</ROOM_LIST>");

strAd.append("<ROOM_LIST>");
strAd.append("<ROOM_NM>금강산호텔 - 스위트(온돌)</ROOM_NM>");
strAd.append("<ROOM_VAL>GHSWO</ROOM_VAL>");
strAd.append("<ROOM_PRI>200000</ROOM_PRI>");
strAd.append("<ROOM_REAL_NUM>2</ROOM_REAL_NUM>");
strAd.append("<ROOM_TOTAL_NUM>10</ROOM_TOTAL_NUM>");
strAd.append("<ROOM_IMG_S>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_S>");
strAd.append("<ROOM_INFO_S>금강산호텔 - 스위트(온돌) 정보 입니다.</ROOM_INFO_S>");
strAd.append("<ROOM_GALLERY_LIST>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>1.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>2.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>3.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M></ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("</ROOM_GALLERY_LIST>");
strAd.append("<ROOM_REV_YN>Y</ROOM_REV_YN>");
strAd.append("</ROOM_LIST>");

strAd.append("<ROOM_LIST>");
strAd.append("<ROOM_NM>금강산호텔 - 디럭스(더블)</ROOM_NM>");
strAd.append("<ROOM_VAL>GHDXD</ROOM_VAL>");
strAd.append("<ROOM_PRI>200000</ROOM_PRI>");
strAd.append("<ROOM_REAL_NUM>2</ROOM_REAL_NUM>");
strAd.append("<ROOM_TOTAL_NUM>10</ROOM_TOTAL_NUM>");
strAd.append("<ROOM_IMG_S>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_S>");
strAd.append("<ROOM_INFO_S>금강산호텔 - 디럭스(더블) 정보 입니다.</ROOM_INFO_S>");
strAd.append("<ROOM_GALLERY_LIST>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>1.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>2.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>3.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M></ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("</ROOM_GALLERY_LIST>");
strAd.append("<ROOM_REV_YN>Y</ROOM_REV_YN>");
strAd.append("</ROOM_LIST>");

strAd.append("<ROOM_LIST>");
strAd.append("<ROOM_NM>금강산호텔 - 디럭스(트윈)</ROOM_NM>");
strAd.append("<ROOM_VAL>GHDXT</ROOM_VAL>");
strAd.append("<ROOM_PRI>200000</ROOM_PRI>");
strAd.append("<ROOM_REAL_NUM>2</ROOM_REAL_NUM>");
strAd.append("<ROOM_TOTAL_NUM>10</ROOM_TOTAL_NUM>");
strAd.append("<ROOM_IMG_S>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_S>");
strAd.append("<ROOM_INFO_S>금강산호텔 - 디럭스(트윈) 정보 입니다.</ROOM_INFO_S>");
strAd.append("<ROOM_GALLERY_LIST>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>1.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>2.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>3.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M></ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("</ROOM_GALLERY_LIST>");
strAd.append("<ROOM_REV_YN>Y</ROOM_REV_YN>");
strAd.append("</ROOM_LIST>");

strAd.append("<ROOM_LIST>");
strAd.append("<ROOM_NM>금강산호텔 스탠다드 트윈</ROOM_NM>");
strAd.append("<ROOM_VAL>GHSTT</ROOM_VAL>");
strAd.append("<ROOM_PRI>200000</ROOM_PRI>");
strAd.append("<ROOM_REAL_NUM>2</ROOM_REAL_NUM>");
strAd.append("<ROOM_TOTAL_NUM></ROOM_TOTAL_NUM>");
strAd.append("<ROOM_IMG_S>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_S>");
strAd.append("<ROOM_INFO_S>금강산호텔 스탠다드 트윈 정보 입니다.</ROOM_INFO_S>");
strAd.append("<ROOM_GALLERY_LIST>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>1.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>2.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>3.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M></ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("</ROOM_GALLERY_LIST>");
strAd.append("<ROOM_REV_YN>Y</ROOM_REV_YN>");
strAd.append("</ROOM_LIST>");

strAd.append("<ROOM_LIST>");
strAd.append("<ROOM_NM>금강산호텔 - 스탠다드(온돌)</ROOM_NM>");
strAd.append("<ROOM_VAL>GHSTT</ROOM_VAL>");
strAd.append("<ROOM_PRI>200000</ROOM_PRI>");
strAd.append("<ROOM_REAL_NUM>2</ROOM_REAL_NUM>");
strAd.append("<ROOM_TOTAL_NUM>10</ROOM_TOTAL_NUM>");
strAd.append("<ROOM_IMG_S>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_S>");
strAd.append("<ROOM_INFO_S>금강산호텔 - 스탠다드(온돌) 트윈 정보 입니다.</ROOM_INFO_S>");
strAd.append("<ROOM_GALLERY_LIST>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>1.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>2.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>3.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("</ROOM_GALLERY>");
strAd.append("</ROOM_GALLERY_LIST>");
strAd.append("<ROOM_REV_YN>Y</ROOM_REV_YN>");
strAd.append("</ROOM_LIST>");

strAd.append("<ROOM_LIST>");
strAd.append("<ROOM_NM>금강산호텔별관 스위트온돌</ROOM_NM>");
strAd.append("<ROOM_VAL>BDSWO</ROOM_VAL>");
strAd.append("<ROOM_PRI>200000</ROOM_PRI>");
strAd.append("<ROOM_REAL_NUM>2</ROOM_REAL_NUM>");
strAd.append("<ROOM_TOTAL_NUM>10</ROOM_TOTAL_NUM>");
strAd.append("<ROOM_IMG_S>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_S>");
strAd.append("<ROOM_INFO_S>금강산호텔별관 스위트온돌 트윈 정보 입니다.</ROOM_INFO_S>");
strAd.append("<ROOM_GALLERY_LIST>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>1.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>2.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>3.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("</ROOM_GALLERY>");
strAd.append("</ROOM_GALLERY_LIST>");
strAd.append("<ROOM_REV_YN>Y</ROOM_REV_YN>");
strAd.append("</ROOM_LIST>");

strAd.append("<ROOM_LIST>");
strAd.append("<ROOM_NM>금강산호텔별관 일반실온돌</ROOM_NM>");
strAd.append("<ROOM_VAL>BDSTO</ROOM_VAL>");
strAd.append("<ROOM_PRI>200000</ROOM_PRI>");
strAd.append("<ROOM_REAL_NUM>2</ROOM_REAL_NUM>");
strAd.append("<ROOM_TOTAL_NUM>10</ROOM_TOTAL_NUM>");
strAd.append("<ROOM_IMG_S>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_S>");
strAd.append("<ROOM_INFO_S>금강산호텔별관 일반실온돌 트윈 정보 입니다.</ROOM_INFO_S>");
strAd.append("<ROOM_GALLERY_LIST>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>1.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>2.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("<ROOM_INFO_M>3.금강산객실 본관 정보 입니다.</ROOM_INFO_M>"); 
strAd.append("</ROOM_GALLERY>");
strAd.append("<ROOM_GALLERY>");
strAd.append("<ROOM_IMG_M>http://www.nate.com/images/thumb/Enter11J/060607_07.gif </ROOM_IMG_M>");
strAd.append("</ROOM_GALLERY>");
strAd.append("</ROOM_GALLERY_LIST>");
strAd.append("<ROOM_REV_YN>Y</ROOM_REV_YN>");
strAd.append("</ROOM_LIST>");
strAd.append("</ROOM>");

out.println(strAd.toString());
%>